//// Users
export const REGISTER_USER_REQUEST = "REGISTER_USER_REQUEST"
export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FAIL = "REGISTER_USER_FAIL"


export const LOGIN_USER_REQUEST = "LOGIN_USER_REQUEST"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"



export const LOGOUT_USER = "LOGOUT_USER"
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL"


export const FORGOT_PASSWORD_EMAIL_REQUEST = "FORGOT_PASSWORD_EMAIL_REQUEST"
export const FORGOT_PASSWORD_EMAIL = "FORGOT_PASSWORD_EMAIL"
export const FORGOT_PASSWORD_EMAIL_FAIL = "FORGOT_PASSWORD_EMAIL_FAIL"
export const FORGOT_PASSWORD_EMAIL_RESET = "FORGOT_PASSWORD_EMAIL_RESET"


export const RESET_PASSWORD_EMAIL_REQUEST = "RESET_PASSWORD_EMAIL_REQUEST"
export const RESET_PASSWORD_EMAIL = "RESET_PASSWORD_EMAIL"
export const RESET_PASSWORD_EMAIL_FAIL = "RESET_PASSWORD_EMAIL_FAIL"
export const RESET_PASSWORD_EMAIL_RESET = "RESET_PASSWORD_EMAIL_RESET"


export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER = "LOAD_USER"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"



export const MY_PROFILE_REQUEST = "MY_PROFILE_REQUEST"
export const MY_PROFILE = "MY_PROFILE"
export const MY_PROFILE_FAIL = "MY_PROFILE_FAIL"



export const UPDATE_PASSWORD_REQUEST = "UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD = "UPDATE_PASSWORD"
export const UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"


export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST" 
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS" 
export const CREATE_POST_FAIL = "CREATE_POST_FAIL" 

export const UPDATE_POST_REQUEST = "UPDATE_POST_REQUEST" 
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS" 
export const UPDATE_POST_FAIL = "UPDATE_POST_FAIL"

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST" 
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS" 
export const DELETE_POST_FAIL = "DELETE_POST_FAIL"

export const GETPOSTOFFOLLOWING_REQUEST = "GETPOSTOFFOLLOWING_REQUEST"
export const GETPOSTOFFOLLOWING_SUCCESS = "GETPOSTOFFOLLOWING_SUCCESS"
export const GETPOSTOFFOLLOWING_FAIL = "GETPOSTOFFOLLOWING_FAIL"

export const LIKEANDUNLIKEPOST_REQUEST = "LIKEANDUNLIKEPOST_REQUEST"
export const LIKEANDUNLIKEPOST_SUCCESS = "LIKEANDUNLIKEPOST_SUCCESS"
export const LIKEANDUNLIKEPOST_FAIL = "LIKEANDUNLIKEPOST_FAIL"


export const COMMENTONPOST_REQUEST = "COMMENTONPOST_REQUEST"
export const COMMENTONPOST_SUCCESS = "COMMENTONPOST_SUCCESS"
export const COMMENTONPOST_FAIL = "COMMENTONPOST_FAIL"

export const DELETECOMMENTPOST_REQUEST = "DELETECOMMENTPOST_REQUEST"
export const DELETECOMMENTPOST_SUCCESS  = "DELETECOMMENTPOST_SUCCESS"
export const DELETECOMMENTPOST_FAIL = "DELETECOMMENTPOST_FAIL"

